-- 集中定义运行策略，数据与算法不得读取方案状态
return {
    aggregate_threshold = 128,
    beam_width = 200,
    candidate_limit = 20,
    confidence_threshold = 0.995,
    early_commit_closed_boundary_threshold = 0.99999,
    early_commit_generations = 3,
    early_commit_maximum_neutral_gap = 3,
    early_commit_retained_raw_length = 3,
    early_commit_strong_generations = 2,
    early_commit_strong_threshold = 0.99999,
    emitted_character_reward = 2.0,
    high_frequency_limit = 1500,
    isolation_lambda = 2.0,
    isolation_threshold = 3000,
    isolation_cache_entries = 8192,
    lexicon_cache_entries = 16384,
    long_input_beam_width = 48,
    long_input_full_beam_length = 24,
    -- 只限制未上屏编码；历史上下文保留用于续句评分
    max_raw_length = 128,
    observed_cache_entries = 32768,
    rank_penalty = 0.03,
    score_cache_entries = 32768,
    supplement_base_reward = 9.0,
    supplement_default_weight = 1000,
    supplement_max_reward = 16.0,
    supplement_max_weight = 1000000000,
    supplement_weight_scale = 2.0,
    whole_input_single_character_reward = 5.0,
}
